### ISSUE TITLE
Problem related with update to version 0.103.5?

### ISSUE THREAD

**Issue by RedWheiler80** [pippyn/Home-Assistant-Sensor-Ophaalkalender#17]
Installed this at the last couple of days of 2019. Seemed to look great to make a new template around and throw away my own written script (yours looks way better written, great job!).

But now I get, on all my services from "Ophaalkalender" the same response... I'm not sure, but it seems this had started after I upgraded HA to 0.103.5?

Thank you in advance!
`Update for sensor.ophaalkalender_restafval fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 281, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 461, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ophaalkalender/sensor.py", line 196, in update
    self.data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/ophaalkalender/sensor.py", line 114, in update
    response = requests.get(url).json()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by erikwachters** [comment]
I have the same problem

**Comment by CervDotBe** [comment]
ophaalkalender service just looks to be unavalaible

**Comment by wimpie007** [comment]
same problem here.

**Comment by RedWheiler80** [comment]
it seems indeed that it's a problem with the website itself. Before you could enter there your details and get the calendar, now that's not possible anymore.

**Comment by wimpie007** [comment]
Seems to be fixed! (website back ok!)
